server:
  port: 9110
management:
  server:
    port: 9111
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env, health

# logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO